version: '3.9'

services:
  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   restart: unless-stopped
  #   ports:
  #     - 8191:8191
  #   environment:
  #     - LOG_LEVEL=info
  #     - LOG_FILE=/data/log.txt
  #     - LOG_MAX_SIZE=10000000
  #     - LOG_MAX_FILES=10
  #   volumes:
  #     - ./data:/data
  #   healthcheck:
  #     test: ['CMD', 'curl', '-f', 'http://flaresolverr:8191']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 0

  app:
    build: .
    # depends_on:
    #   flaresolverr:
    #     condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./:/app/
